/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ufidelitas.pantallas;

import com.ufidelitas.data.GestionUsuario;
import com.ufidelitas.modelo.Usuario;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author isaac
 */
public class JfrmIniciarSesión extends javax.swing.JFrame {

    /**
     * Creates new form JfrmIniciarSesión
     */
    public JfrmIniciarSesión() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtIniciarSesion = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jPwdContrasennia = new javax.swing.JPasswordField();
        lblRegistrarse = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inicio de sesión");
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setLabelFor(jTxtCorreo);
        jLabel1.setText("Correo electrónico");

        jLabel2.setLabelFor(jPwdContrasennia);
        jLabel2.setText("Contraseña");

        jTxtIniciarSesion.setText("Iniciar sesión");
        jTxtIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtIniciarSesionActionPerformed(evt);
            }
        });

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        lblRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRegistrarse.setForeground(new java.awt.Color(51, 51, 255));
        lblRegistrarse.setText("Registrate aquí!");
        lblRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarseMouseClicked(evt);
            }
        });

        jLabel4.setText("¿Todavía no te has registrado?");

        jLblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblRegistrarse))
                    .addComponent(jLabel1)
                    .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jPwdContrasennia, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(jPwdContrasennia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistrarse)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarseMouseClicked
        JfrmRegistrarse registrarse = new JfrmRegistrarse();
        registrarse.setVisible(true);
        registrarse.setLocationRelativeTo(null);

        this.dispose();
    }//GEN-LAST:event_lblRegistrarseMouseClicked

    public boolean validarCorreoElectronico(String correo) {
        String regex = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(correo);
        return matcher.matches();
    }

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTxtIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtIniciarSesionActionPerformed
        Usuario usuario = null;

        if (!validarCorreoElectronico(jTxtCorreo.getText())) {
            JOptionPane.showMessageDialog(null, "El correo electrónico ingresado no es correcto", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        char[] passwordChars = jPwdContrasennia.getPassword();
        String password = new String(passwordChars);

        if (password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar la contraseña", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        GestionUsuario gestionUsuario = new GestionUsuario();
        gestionUsuario.validarUsuarioAsync(jTxtCorreo.getText(), password, new GestionUsuario.Callback<Usuario>() {
            @Override
            public void onResult(Usuario usuario) {
                if (usuario == null) {
                    JOptionPane.showMessageDialog(null, "Usuario no encontrado en el sistema", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                JfrmRestaurantes.setUsuarioActual(usuario);
                JfrmRestaurantes restaurantes = new JfrmRestaurantes();
                restaurantes.setVisible(true);
                restaurantes.setLocationRelativeTo(null);
                dispose();
            }
        });
    }//GEN-LAST:event_jTxtIniciarSesionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblLogo;
    private javax.swing.JPasswordField jPwdContrasennia;
    private javax.swing.JTextField jTxtCorreo;
    private javax.swing.JButton jTxtIniciarSesion;
    private javax.swing.JLabel lblRegistrarse;
    // End of variables declaration//GEN-END:variables
}
