/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ufidelitas.pantallas;

import com.ufidelitas.data.GestionImpuestos;
import com.ufidelitas.data.GestionProducto;
import com.ufidelitas.data.GestionPedidos;
import com.ufidelitas.data.GestionRestaurantes;
import com.ufidelitas.modelo.Impuesto;
import com.ufidelitas.modelo.Producto;
import com.ufidelitas.modelo.Restaurante;
import com.ufidelitas.modelo.Usuario;
import java.net.URL;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author isaac
 */
public class JfrmRestaurantes extends javax.swing.JFrame {

    private static Usuario usuarioActual;

    public static Usuario getUsuarioActual() {
        return usuarioActual;
    }

    public static void setUsuarioActual(Usuario usuarioActual) {
        JfrmRestaurantes.usuarioActual = usuarioActual;
    }

    GestionProducto gestionMenu = new GestionProducto();
    GestionPedidos gestionPedidos = new GestionPedidos();
    GestionImpuestos gestionImpuestos = new GestionImpuestos();

    int codigoMenu = 0;
    double total;
    Impuesto impuesto;

    Producto menuSeleccionado;
    Producto menuDelCarrito;

    JfrmMenuDelRestaurante interfazMenu;

    private static List<Producto> carrito = new ArrayList<>();
    DefaultListModel<Producto> modelCarrito = new DefaultListModel<>();

    public static void agregarMenu(Producto menu) {
        carrito.add(menu);
    }

    public static List<Producto> getCarrito() {
        return carrito;
    }

    public JfrmRestaurantes() {
        initComponents();
        MostrarUsuario();
        CargarRestaurantes();
        MostrarCarrito();
        OcultarCarrito();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jBtnCerrarSesion = new javax.swing.JButton();
        jPnlCarrito = new javax.swing.JPanel();
        jBtnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLstCarrito = new javax.swing.JList<>();
        jBtnEliminar = new javax.swing.JButton();
        jSpnCantidad = new javax.swing.JSpinner();
        jLblMenuSeleccionado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnCambiarCantidad = new javax.swing.JButton();
        jLblPrecio = new javax.swing.JLabel();
        jLblSubTotal = new javax.swing.JLabel();
        jLblTotal = new javax.swing.JLabel();
        jBtnRealizarPedido = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jRdbTarjeta = new javax.swing.JRadioButton();
        jRdbEfectivo = new javax.swing.JRadioButton();
        jLblNombreUsuario = new javax.swing.JLabel();
        jPnlKFC = new javax.swing.JPanel();
        jLblLogoRestaurante = new javax.swing.JLabel();
        jLblNombreRestaurante = new javax.swing.JLabel();
        jLblMenu1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLblMenu2 = new javax.swing.JLabel();
        jLblMenu3 = new javax.swing.JLabel();
        jLblMenu4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLblDireccionRestaurante = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jRdbRápida = new javax.swing.JRadioButton();
        jRdbItaliana = new javax.swing.JRadioButton();
        jRdbMexicana = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 161, -1));

        jBtnCerrarSesion.setText("Cerrar sesión");
        jBtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 120, 30));

        jPnlCarrito.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carrito de compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jBtnLimpiar.setText("Limpiar el carrito");
        jBtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarActionPerformed(evt);
            }
        });

        jLstCarrito.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLstCarrito.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLstCarritoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jLstCarrito);

        jBtnEliminar.setText("Eliminar del carrito");
        jBtnEliminar.setEnabled(false);
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jSpnCantidad.setDoubleBuffered(true);
        jSpnCantidad.setEditor(new javax.swing.JSpinner.NumberEditor(jSpnCantidad, ""));
        jSpnCantidad.setEnabled(false);

        jLblMenuSeleccionado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel4.setText("Cantidad seleccionada");

        jBtnCambiarCantidad.setText("Cambiar cantidad");
        jBtnCambiarCantidad.setEnabled(false);
        jBtnCambiarCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCambiarCantidadActionPerformed(evt);
            }
        });

        jBtnRealizarPedido.setText("Realizar pedido");
        jBtnRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRealizarPedidoActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elija el método de pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        buttonGroup2.add(jRdbTarjeta);
        jRdbTarjeta.setSelected(true);
        jRdbTarjeta.setText("Tarjeta");

        buttonGroup2.add(jRdbEfectivo);
        jRdbEfectivo.setText("Efectivo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jRdbTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRdbEfectivo)
                .addGap(80, 80, 80))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRdbTarjeta)
                    .addComponent(jRdbEfectivo))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnlCarritoLayout = new javax.swing.GroupLayout(jPnlCarrito);
        jPnlCarrito.setLayout(jPnlCarritoLayout);
        jPnlCarritoLayout.setHorizontalGroup(
            jPnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPnlCarritoLayout.createSequentialGroup()
                .addGroup(jPnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlCarritoLayout.createSequentialGroup()
                        .addGroup(jPnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlCarritoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addGroup(jPnlCarritoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPnlCarritoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlCarritoLayout.createSequentialGroup()
                                .addComponent(jLblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnRealizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnlCarritoLayout.createSequentialGroup()
                                .addGroup(jPnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(jPnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnCambiarCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlCarritoLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(jPnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblMenuSeleccionado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlCarritoLayout.createSequentialGroup()
                                .addGroup(jPnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)))))
                .addContainerGap())
        );
        jPnlCarritoLayout.setVerticalGroup(
            jPnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCarritoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLblMenuSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addGroup(jPnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCambiarCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPnlCarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnRealizarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPnlCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 450, 560));

        jLblNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jLblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 70, 170, 26));

        jPnlKFC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles del restaurante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLblLogoRestaurante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblLogoRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pngegg.png"))); // NOI18N

        jLblNombreRestaurante.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jLblMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kfc1.png"))); // NOI18N
        jLblMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblMenu1MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Elija el producto que desea");

        jLblMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kfc2.png"))); // NOI18N
        jLblMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblMenu2MouseClicked(evt);
            }
        });

        jLblMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kfc3.png"))); // NOI18N
        jLblMenu3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblMenu3MouseClicked(evt);
            }
        });

        jLblMenu4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLblMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kfc4.png"))); // NOI18N
        jLblMenu4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblMenu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLblMenu4MouseClicked(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLblDireccionRestaurante.setColumns(20);
        jLblDireccionRestaurante.setLineWrap(true);
        jLblDireccionRestaurante.setRows(5);
        jLblDireccionRestaurante.setBorder(null);
        jScrollPane2.setViewportView(jLblDireccionRestaurante);

        javax.swing.GroupLayout jPnlKFCLayout = new javax.swing.GroupLayout(jPnlKFC);
        jPnlKFC.setLayout(jPnlKFCLayout);
        jPnlKFCLayout.setHorizontalGroup(
            jPnlKFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPnlKFCLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPnlKFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPnlKFCLayout.createSequentialGroup()
                        .addGroup(jPnlKFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPnlKFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPnlKFCLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblLogoRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPnlKFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblNombreRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPnlKFCLayout.setVerticalGroup(
            jPnlKFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlKFCLayout.createSequentialGroup()
                .addGroup(jPnlKFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlKFCLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLblNombreRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlKFCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLblLogoRestaurante)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(jPnlKFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnlKFCLayout.createSequentialGroup()
                        .addGroup(jPnlKFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLblMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLblMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLblMenu4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPnlKFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 125, 620, 680));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elija el tipo de restaurante que desea", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        buttonGroup1.add(jRdbRápida);
        jRdbRápida.setSelected(true);
        jRdbRápida.setText("Comida Rápida");
        jRdbRápida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbRápidaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRdbItaliana);
        jRdbItaliana.setText("Comida Italiana");
        jRdbItaliana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbItalianaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRdbMexicana);
        jRdbMexicana.setText("Comida Mexicana");
        jRdbMexicana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbMexicanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jRdbRápida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jRdbItaliana)
                .addGap(26, 26, 26)
                .addComponent(jRdbMexicana)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRdbRápida)
                    .addComponent(jRdbItaliana)
                    .addComponent(jRdbMexicana))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 19, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLblMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblMenu1MouseClicked

        if (jRdbRápida.isSelected()) {
            codigoMenu = 1;

        } else if (jRdbMexicana.isSelected()) {
            codigoMenu = 5;

        } else if (jRdbItaliana.isSelected()) {
            codigoMenu = 9;
        }

        agregarMenu(codigoMenu);
    }//GEN-LAST:event_jLblMenu1MouseClicked

    private void jLblMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblMenu2MouseClicked

        if (jRdbRápida.isSelected()) {
            codigoMenu = 2;

        } else if (jRdbMexicana.isSelected()) {
            codigoMenu = 6;

        } else if (jRdbItaliana.isSelected()) {
            codigoMenu = 10;
        }

        agregarMenu(codigoMenu);
    }//GEN-LAST:event_jLblMenu2MouseClicked

    private void jLblMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblMenu3MouseClicked

        if (jRdbRápida.isSelected()) {
            codigoMenu = 3;

        } else if (jRdbMexicana.isSelected()) {
            codigoMenu = 7;

        } else if (jRdbItaliana.isSelected()) {
            codigoMenu = 11;
        }

        agregarMenu(codigoMenu);
    }//GEN-LAST:event_jLblMenu3MouseClicked

    private void jLblMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblMenu4MouseClicked

        if (jRdbRápida.isSelected()) {
            codigoMenu = 4;

        } else if (jRdbMexicana.isSelected()) {
            codigoMenu = 8;

        } else if (jRdbItaliana.isSelected()) {
            codigoMenu = 12;
        }

        agregarMenu(codigoMenu);
    }//GEN-LAST:event_jLblMenu4MouseClicked

    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
        carrito.clear();
        modelCarrito.clear();

        jLblMenuSeleccionado.setText("");
        jSpnCantidad.setValue(0);
        OcultarCarrito();
    }//GEN-LAST:event_jBtnLimpiarActionPerformed

    private void jLstCarritoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLstCarritoValueChanged
        menuDelCarrito = jLstCarrito.getSelectedValue();

        if (menuDelCarrito != null) {
            jBtnEliminar.setEnabled(true);
            jBtnCambiarCantidad.setEnabled(true);
            jSpnCantidad.setEnabled(true);

            jLblMenuSeleccionado.setText(menuDelCarrito.getNombre());
            jSpnCantidad.setValue((Integer) menuDelCarrito.getCantidadAcomprar());
            RealizarCalculos();
        }
    }//GEN-LAST:event_jLstCarritoValueChanged

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        if (menuDelCarrito != null) {
            Iterator<Producto> iterator = carrito.iterator();
            while (iterator.hasNext()) {
                Producto menu = iterator.next();
                if (menu.getId() == menuDelCarrito.getId()) {
                    iterator.remove();
                    break;
                }
            }

            modelCarrito.clear();
            if (!carrito.isEmpty()) {
                for (Producto menu : carrito) {
                    modelCarrito.addElement(menu);
                }
            }

            jLblMenuSeleccionado.setText("");
            jSpnCantidad.setValue(0);
            jLblPrecio.setText("");
            jLblSubTotal.setText("");

            jBtnEliminar.setEnabled(false);
            jBtnCambiarCantidad.setEnabled(false);
            jSpnCantidad.setEnabled(false);

            OcultarCarrito();
            RealizarCalculos();
        }
    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jBtnCambiarCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCambiarCantidadActionPerformed
        if (menuDelCarrito != null) {
            int cantidad = (Integer) jSpnCantidad.getValue();
            Iterator<Producto> iterator = carrito.iterator();

            while (iterator.hasNext()) {
                Producto menu = iterator.next();
                if (cantidad <= 0) {
                    iterator.remove();
                    break;
                }

                if (menu.getId() == menuDelCarrito.getId()) {
                    menu.setCantidadAcomprar(cantidad);
                    break;
                }
            }

            modelCarrito.clear();
            if (!carrito.isEmpty()) {
                for (Producto menu : carrito) {
                    modelCarrito.addElement(menu);
                }
            }

            jLblMenuSeleccionado.setText("");
            jSpnCantidad.setValue(0);
            OcultarCarrito();
            jBtnEliminar.setEnabled(false);
            jBtnCambiarCantidad.setEnabled(false);
            jSpnCantidad.setEnabled(false);

            jLblPrecio.setText("");
            jLblSubTotal.setText("");
            RealizarCalculos();
        }
    }//GEN-LAST:event_jBtnCambiarCantidadActionPerformed

    private void jBtnRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRealizarPedidoActionPerformed
        int metodoPago = jRdbTarjeta.isSelected() ? 1 : 2;
        gestionPedidos.insertarPedido(total, carrito, usuarioActual, metodoPago, impuesto);
        
        jFrmPedido.setCarrito(carrito);
        jFrmPedido frmPedido = new jFrmPedido(); 
        
        carrito.clear();
        modelCarrito.clear();
        OcultarCarrito();  
        
        frmPedido.setVisible(true);
        frmPedido.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_jBtnRealizarPedidoActionPerformed

    private void jBtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarSesionActionPerformed
        JfrmIniciarSesión login = new JfrmIniciarSesión();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarSesionActionPerformed

    private void jRdbRápidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbRápidaActionPerformed
        CargarRestaurantes();
        CargarImagenes();
    }//GEN-LAST:event_jRdbRápidaActionPerformed

    private void jRdbItalianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbItalianaActionPerformed
        CargarRestaurantes();
        CargarImagenes();
    }//GEN-LAST:event_jRdbItalianaActionPerformed

    private void jRdbMexicanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbMexicanaActionPerformed
        CargarRestaurantes();
        CargarImagenes();
    }//GEN-LAST:event_jRdbMexicanaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBtnCambiarCantidad;
    private javax.swing.JButton jBtnCerrarSesion;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JButton jBtnRealizarPedido;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextArea jLblDireccionRestaurante;
    private javax.swing.JLabel jLblLogoRestaurante;
    private javax.swing.JLabel jLblMenu1;
    private javax.swing.JLabel jLblMenu2;
    private javax.swing.JLabel jLblMenu3;
    private javax.swing.JLabel jLblMenu4;
    private javax.swing.JLabel jLblMenuSeleccionado;
    private javax.swing.JLabel jLblNombreRestaurante;
    private javax.swing.JLabel jLblNombreUsuario;
    private javax.swing.JLabel jLblPrecio;
    private javax.swing.JLabel jLblSubTotal;
    private javax.swing.JLabel jLblTotal;
    private javax.swing.JList<com.ufidelitas.modelo.Producto> jLstCarrito;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPnlCarrito;
    private javax.swing.JPanel jPnlKFC;
    private javax.swing.JRadioButton jRdbEfectivo;
    private javax.swing.JRadioButton jRdbItaliana;
    private javax.swing.JRadioButton jRdbMexicana;
    private javax.swing.JRadioButton jRdbRápida;
    private javax.swing.JRadioButton jRdbTarjeta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpnCantidad;
    // End of variables declaration//GEN-END:variables

    private void CargarRestaurantes() {
        GestionRestaurantes gestionRestaurantes = new GestionRestaurantes();
        List<Restaurante> restaurantes = gestionRestaurantes.colsultarRestaurantes();

        for (Restaurante restaurante : restaurantes) {
            if (jRdbRápida.isSelected() && restaurante.getCategoria() == 3) {
                jLblNombreRestaurante.setText(restaurante.getNombre());
                jLblDireccionRestaurante.setText(restaurante.getUbicacion());

            } else if (jRdbItaliana.isSelected() && restaurante.getCategoria() == 2) {
                jLblNombreRestaurante.setText(restaurante.getNombre());
                jLblDireccionRestaurante.setText(restaurante.getUbicacion());

            } else if (jRdbMexicana.isSelected() && restaurante.getCategoria() == 1) {
                jLblNombreRestaurante.setText(restaurante.getNombre());
                jLblDireccionRestaurante.setText(restaurante.getUbicacion());
            }
        }
    }

    private void mostrarMenu() {
        JfrmMenuDelRestaurante.setMenu(menuSeleccionado);
        interfazMenu = new JfrmMenuDelRestaurante();
        interfazMenu.setVisible(true);
        interfazMenu.setLocationRelativeTo(this);
        this.dispose();
    }

    private void MostrarCarrito() {
        if (!carrito.isEmpty()) {
            for (Producto menu : carrito) {
                modelCarrito.addElement(menu);
            }

            jPnlCarrito.setVisible(true);
            jLstCarrito.setModel(modelCarrito);

            RealizarCalculos();
        }
    }

    private void OcultarCarrito() {
        if (carrito.isEmpty()) {

            jPnlCarrito.setVisible(false);
        }
    }

    private void RealizarCalculos() {
        total = 0;
        double precio = 0;
        double subTotal = 0;
        impuesto = gestionImpuestos.consultarImpuesto(1);

        if (menuDelCarrito != null) {
            precio = menuDelCarrito.getPrecio();
            subTotal = precio * menuDelCarrito.getCantidadAcomprar();
            subTotal = subTotal + (subTotal * (impuesto.getValor() / 100.0));

            jLblPrecio.setText("Precio del menú: ₡" + precio);
            jLblSubTotal.setText("Subtotal del menú: ₡" + subTotal + " + IVA: 13");
        }

        for (Producto menu : carrito) {
            subTotal = menu.getPrecio() * menu.getCantidadAcomprar();
            subTotal = subTotal + (subTotal * (impuesto.getValor() / 100.0));
            menu.setSubTotal(subTotal);
            total += subTotal;
        }
        
        DecimalFormat decimalFormat = new DecimalFormat("0.00");
        String formattedTotal = decimalFormat.format(total);

        jLblTotal.setText("Total de la compra: ₡" + formattedTotal);
    }

    private void MostrarUsuario() {
        jLblNombreUsuario.setText(usuarioActual.getNombre());
    }

    private boolean comprobarEnCarrito(int idMenu) {
        boolean bandera = false;

        if (!carrito.isEmpty()) {
            for (Producto menu : carrito) {
                if (menu.getId() == idMenu) {
                    JOptionPane.showMessageDialog(null, "Este menú ya ha sido agregado al carrito",
                            "Advertencia", JOptionPane.WARNING_MESSAGE);
                    bandera = true;
                    break;
                }
            }
        }

        return bandera;
    }

    private void agregarMenu(int codigoMenu) {
        menuSeleccionado = gestionMenu.consultarProductoPorCodigo(codigoMenu);
        if (menuSeleccionado != null && !comprobarEnCarrito(codigoMenu)) {
            mostrarMenu();
        }
    }

    private void CargarImagenes() {
        URL logoUrl = null, menu1 = null, menu2 = null, menu3 = null, menu4 = null;
        ClassLoader classLoader = getClass().getClassLoader();

        try {
            if (jRdbRápida.isSelected()) {
                logoUrl = classLoader.getResource("images/pngegg.png");
                menu1 = classLoader.getResource("images/kfc1.png");
                menu2 = classLoader.getResource("images/kfc2.png");
                menu3 = classLoader.getResource("images/kfc3.png");
                menu4 = classLoader.getResource("images/kfc4.png");

            } else if (jRdbItaliana.isSelected()) {
                logoUrl = classLoader.getResource("images/papaJohnsLogo.png");
                menu1 = classLoader.getResource("images/papaJhons1.jpg");
                menu2 = classLoader.getResource("images/papaJhons2.jpg");
                menu3 = classLoader.getResource("images/papaJhons3.jpg");
                menu4 = classLoader.getResource("images/papaJhons4.jpg");

            } else if (jRdbMexicana.isSelected()) {
                logoUrl = classLoader.getResource("images/tacoBellLogo.png");
                menu1 = classLoader.getResource("images/tacobell1.png");
                menu2 = classLoader.getResource("images/tacobell2.png");
                menu3 = classLoader.getResource("images/tacobell3.png");
                menu4 = classLoader.getResource("images/tacobell4.png");
            }

            if (logoUrl != null && menu1 != null && menu2 != null && menu3 != null && menu4 != null) {
                ImageIcon icon = new ImageIcon(logoUrl);
                jLblLogoRestaurante.setIcon(icon);

                icon = new ImageIcon(menu1);
                jLblMenu1.setIcon(icon);

                icon = new ImageIcon(menu2);
                jLblMenu2.setIcon(icon);

                icon = new ImageIcon(menu3);
                jLblMenu3.setIcon(icon);

                icon = new ImageIcon(menu4);
                jLblMenu4.setIcon(icon);

            } else {
                System.err.println("No se pudo encontrar la imagen en el directorio resources/images.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
